### ISSUE TITLE
Not compatible with ember-cli@2.13

### ISSUE THREAD

**Issue by aexmachina** [ember-cli/ember-cli-mocha#182] opened 2017-03-23 01:52 UTC
I just created a clean test project with ember-cli@2.13 using `ember new ember-test --yarn` then ran `ember install ember-cli-mocha` and now `ember s` fails with the following error message:

```
$ ember s
Livereload server on http://localhost:49153
File: ember-mocha.js
The Broccoli Plugin: [broccoli-persistent-filter:Babel > [Babel: Ember CLI Mocha]: Babel: Ember CLI Mocha] failed with:
TypeError: The plugin [null,{}] didn't export a Plugin instance
    at PluginManager.validate (/Users/simonwade/Temp/test-ember/node_modules/babel-core/lib/transformation/file/plugin-manager.js:164:13)
    at PluginManager.add (/Users/simonwade/Temp/test-ember/node_modules/babel-core/lib/transformation/file/plugin-manager.js:213:10)
    at File.buildTransformers (/Users/simonwade/Temp/test-ember/node_modules/babel-core/lib/transformation/file/index.js:237:21)
    at new File (/Users/simonwade/Temp/test-ember/node_modules/babel-core/lib/transformation/file/index.js:139:10)
    at Pipeline.transform (/Users/simonwade/Temp/test-ember/node_modules/babel-core/lib/transformation/pipeline.js:164:16)
    at Babel.transform (/Users/simonwade/Temp/test-ember/node_modules/ember-cli-mocha/node_modules/broccoli-babel-transpiler/index.js:107:21)
    at Babel.processString (/Users/simonwade/Temp/test-ember/node_modules/ember-cli-mocha/node_modules/broccoli-babel-transpiler/index.js:206:25)
    at Promise.then.result.output (/Users/simonwade/Temp/test-ember/node_modules/broccoli-persistent-filter/lib/strategies/persistent.js:41:23)
    at initializePromise (/Users/simonwade/Temp/test-ember/node_modules/rsvp/dist/rsvp.js:589:5)
    at new Promise$1 (/Users/simonwade/Temp/test-ember/node_modules/rsvp/dist/rsvp.js:1077:33)

The broccoli plugin was instantiated at:
    at Babel.Plugin (/Users/simonwade/Temp/test-ember/node_modules/broccoli-plugin/index.js:7:31)
    at Babel.Filter [as constructor] (/Users/simonwade/Temp/test-ember/node_modules/broccoli-persistent-filter/index.js:62:10)
    at new Babel (/Users/simonwade/Temp/test-ember/node_modules/ember-cli-mocha/node_modules/broccoli-babel-transpiler/index.js:35:10)
    at Babel (/Users/simonwade/Temp/test-ember/node_modules/ember-cli-mocha/node_modules/broccoli-babel-transpiler/index.js:30:12)
    at Object.toTree (/Users/simonwade/Temp/test-ember/node_modules/ember-cli-mocha/node_modules/ember-cli-babel/index.js:30:52)
    at /Users/simonwade/Temp/test-ember/node_modules/ember-cli-preprocess-registry/preprocessors.js:180:26
    at Array.forEach (native)
    at processPlugins (/Users/simonwade/Temp/test-ember/node_modules/ember-cli-preprocess-registry/preprocessors.js:178:11)
    at Function.module.exports.preprocessJs (/Users/simonwade/Temp/test-ember/node_modules/ember-cli-preprocess-registry/preprocessors.js:171:10)
    at Class.preprocessJs (/Users/simonwade/Temp/test-ember/node_modules/ember-cli/lib/models/addon.js:1104:25)
```

**Comment by rwjblue** [comment] 2017-03-23 02:07
What is your environment?  Is this under npm@2, npm@3, yarn, etc? What node version?

**Comment by rwjblue** [comment] 2017-03-23 02:07
Can you push up a demo app, including `node_modules`, so we can take a look at what is going on?

**Comment by aexmachina** [comment] 2017-03-23 02:13
Sorry, I should have indicated I used `ember new test-ember --yarn` with `yarn@0.18.1` and `node@7.6.0`.

**Comment by aexmachina** [comment] 2017-03-23 02:16
Pushing to https://github.com/aexmachina/ember-cli-mocha-182...

**Comment by aexmachina** [comment] 2017-03-23 02:19
That's pushed now

**Comment by Turbo87** [comment] 2017-03-23 08:01
I can reproduce this with just:

- `ember new foo --yarn`
- `cd foo`
- `ember install ember-cli-mocha`
- `ember serve`

@aexmachina thanks for the reproduction!

**Comment by Turbo87** [comment] 2017-03-23 08:08
```
$ yarn list broccoli-babel-transpiler
yarn list v0.21.3
├─ broccoli-babel-transpiler@5.6.2
├─ ember-cli-babel@6.0.0-beta.9
│  └─ broccoli-babel-transpiler@6.0.0
├─ ember-cli@2.13.0-beta.2
│  └─ broccoli-babel-transpiler@6.0.0-alpha.3
└─ ember-data@2.13.0-beta.3
│  └─ broccoli-babel-transpiler@6.0.0
```

**Comment by rwjblue** [comment] 2017-04-01 00:22
Good news!! I have determined the issue here...

It comes down to issues with `npm` non-determinism. I have a solution, but it will involve fixes upstream in ember-cli.

**Comment by Turbo87** [comment] 2017-04-01 00:40
cool, thanks!

**Comment by stefanpenner** [comment] 2017-04-17 20:01
> I have a solution

Just spoke to @rwjblue, the solution is:

No longer trust npm to do `npm install <package>`, because they appear to only consider `<package>` dependencies, not the full graph. They bork stuff up. We should confirm that `latest` `yarn` has or doesn't have this problem. If it does, the solution for us would be either:

* do nothing, tell people to `rimraf node_modules` and try again
* on `packageInstall` manually update `package.json` to include the new or updated version, and then run `npm install`.

**Comment by stefanpenner** [comment] 2017-04-17 20:02
@Turbo87 I suspect we want to do the second one, as this will give a better user experience. What are your thoughts?

**Comment by Turbo87** [comment] 2017-04-17 20:38
@stefanpenner I'm not yet convinced that this is actually the issue or solution. I'd be very surprised if npm would be *that* broken. I'm instead suspecting that something is not resolving from the correct cwd.

**Comment by Turbo87** [comment] 2017-04-17 20:39
Also I had the same issue with yarn, and yarn is supposed to have stable output which seems to be another hint that something else might be wrong.

**Comment by stefanpenner** [comment] 2017-04-17 21:04
@Turbo87 ah, ok. So it sounds like this needs more exploration?

**Comment by Turbo87** [comment] 2017-04-18 07:01
> it sounds like this needs more exploration?

yes. the problem is that I am not aware of what could have caused this to break in Ember CLI itself since it all works fine with the v2.12 releases.

**Comment by runspired** [comment] 2017-04-18 14:59
Also, fwiw, I've noticed this in prior ember-cli releases, but it's become more problematic recently because of the babel6 upgrade and a few other dependency bumps.  I don't think this is an issue with ember-cli because I have been able manually recreate this problem without the involvement of any cli commands.

**Comment by Turbo87** [comment] 2017-04-18 15:44
> npm is that broken, I deal with this particular bug often

what particular bug are you talking about? I'm not sure we're all talking about the same things here...

> I don't think this is an issue with ember-cli

since downgrading ember-cli to v2.12 solves the issue I'm pretty sure it is an issue in ember-cli or at least surfaced by ember-cli v2.13-beta

**Comment by kevinansfield** [comment] 2017-04-21 15:44
I've tried upgrading Ghost to ember-cli v2.13-beta.3 to test and have also run into this issue.

yarn: v0.23.2
node: v6.10.1 (alto tested with with same issue on v4.8.1)

`rm -rf node_modules && yarn install` made no difference

If there's any other info I can provide to help track the issue down please let me know. My test branch [is here](https://github.com/kevinansfield/Ghost-Admin/tree/ember-cli-targets) if it's of any use

**Comment by Turbo87** [comment] 2017-04-21 21:07
result of `git bisect` looks a little confusing to me... 🤔 

```
fddbc4a111bb2ec57170e2648a5fc37e2036c422 is the first bad commit
commit fddbc4a111bb2ec57170e2648a5fc37e2036c422
Author: Tobias Bieniek <tobias.bieniek@gmail.com>
Date:   Thu Mar 16 13:00:23 2017 +0100

    Release v2.13.0-beta.1
```

**Comment by rwjblue** [comment] 2017-04-21 21:42
Submitted the fix in #190

**Closed** 2017-04-21 22:01 UTC
Labels: bug

**Comment by aexmachina** [comment] 2017-04-24 01:38
Thanks @rwjblue 👍

**Comment by alexlafroscia** [comment] 2017-05-07 03:27
I'm still having issues with this, trying to upgrade `ember-ajax`.  My `devDependencies` are:

```json
{
  "broccoli-asset-rev": "^2.4.5",
  "coveralls": "^2.13.0",
  "ember-cli": "^2.13.1",
  "ember-cli-chai": "^0.4.0",
  "ember-cli-code-coverage": "^0.3.12",
  "ember-cli-dependency-checker": "^1.4.0",
  "ember-cli-eslint": "^3.1.0",
  "ember-cli-htmlbars": "^1.3.0",
  "ember-cli-htmlbars-inline-precompile": "^0.4.0",
  "ember-cli-inject-live-reload": "^1.4.1",
  "ember-cli-mocha": "^0.14.2",
  "ember-cli-pretender": "^1.0.1",
  "ember-cli-release": "^1.0.0-beta.2",
  "ember-cli-shims": "1.1.0",
  "ember-cli-sri": "^2.1.0",
  "ember-cli-test-loader": "^2.1.0",
  "ember-cli-testdouble": "0.1.0",
  "ember-cli-uglify": "^1.2.0",
  "ember-data": "^2.12.2",
  "ember-disable-prototype-extensions": "^1.1.0",
  "ember-export-application-global": "2.0.0",
  "ember-load-initializers": "1.0.0",
  "ember-resolver": "4.1.0",
  "ember-source": "^2.12.1",
  "eslint": "^3.19.0",
  "eslint-plugin-ember-suave": "^1.0.0",
  "loader.js": "^4.3.0",
  "testdouble-chai": "^0.5.0"
}
```

even with the most recent version of `ember-cli-mocha` the babel error occurs.
